apiVersion: v1
kind: Service
metadata:
  name: svc-node-cosmos
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: node-cosmos
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-cosmos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-cosmos
  template:
    metadata:
      labels:
        app: node-cosmos
    spec:
      containers:
      - name: node-cosmos
        image: ashwilliams/clinicavet:v6
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080" 
        - name: COSMOSDB_URI
          valueFrom:
            secretKeyRef:
              name: cosmosdb-secret
              key: conn-string    