apiVersion: v1
kind: Secret
metadata:
  name: cosmosdb-secret
type: Opaque
stringData:
  conn-string: 'mongodb://clinica:Vw3GPNnZWkMdRXdV34RMOD9ZrH5qzXXiudAXzOtXUJD05UnVRZ1OS06R5gfrw0TGMhpcRt4WTQdWiVWbmcEERg%3D%3D@clinica.mongo.cosmos.azure.com:10255/petstore?ssl=true'
